### ISSUE TITLE
Approximate cost?

### ISSUE THREAD

**Issue by cweagans** [maxvfischer/DIY-CNC-machine#2]
If I was going to build this, what would the approximate materials cost be?

**Comment by maxvfischer** [comment]
I ended up paying around $1100 in total, but then I paid for the fastest shipping, ordered some parts that I ended up not using and spent 3d-printing filament on parts I had to redesign and reprint. So I would say between $600-$1500 depending on where your source the parts from (Aliexpress or high-end website), how fast you want it delivered, where you live etc.
