### ISSUE TITLE
Print parameters

### ISSUE THREAD

**Issue by pgrudzien1987** [maxvfischer/DIY-CNC-machine#6]
Is somewhere information about print parameters for 3d elements? I mean infill percentage for instance.
Also what kind of material do you recommended? PLA/PETG?

**Comment by maxvfischer** [comment]
I just pushed my PrusaSlicer config to the repo and added information about infill etc to the BOM.

I printed everything in PLA, using the folloing settings:

- 30% infill
- 4 top solid horizontal layers
- 4 bottom solid horizontal layers
- 4 perimeters
