### ISSUE TITLE
How to make US version?

### ISSUE THREAD

**Issue by tenumars** [maxvfischer/DIY-CNC-machine#8]
The title is pretty self-explanatory, is there a way to get the drill and other parts in USA format? And if so, do any of the parts need to be changed for the different voltage? Thanks

**Comment by tenumars** [comment]
In just looking for the router, in case anyone is having the same issue, I found a US version on amazon
[https://us.amazon.com/gp/product/B00E7D3V4S/ref=ox_sc_act_title_1?smid=ATVPDKIKX0DER&th=1](https://us.amazon.com/gp/product/B00E7D3V4S/ref=ox_sc_act_title_1?smid=ATVPDKIKX0DER&th=1)
Not an affiliate link

**Comment by maxvfischer** [comment]
Hey! When buying Ivan's blueprints, he includes .STL-files adjusted for inches and common american parts (square tubes etc). Also, you'll get access to a Discord channel with people who have built the machine, and I would guess that some of them have used the american .STL-files and measurements.

So I would recommend you to buy the blueprints for $25 and then ask all the questions in the Discord channel. People are really helpful there :)

Link to blueprints: https://ivanmiranda.com/products/3d-printed-cnc

**Comment by tenumars** [comment]
Ok, thanks, will do! From: Max FischerSent: Tuesday, March 22, 2022 5:49 AMTo: maxvfischer/DIY-CNC-machineCc: tenumars; AuthorSubject: Re: [maxvfischer/DIY-CNC-machine] How to make US version? (Issue #8) Hey! When buying Ivan's blueprints, he includes .STL-files adjusted for inches and common american parts (square tubes etc). Also, you'll get access to a Discord channel with people who have built the machine, and I would guess that some of them have used the american .STL-files and measurements.So I would recommend you to buy the blueprints for $25 and then ask all the questions in the Discord channel. People are really helpful there :)Link to blueprints: https://ivanmiranda.com/products/3d-printed-cnc—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
